hero.build('cannon', 'F');
hero.build('cannon', 'G');
hero.build('cannon', 'I');
hero.build('cannon', 'H');
hero.build('mage', 29, 52);
hero.build('archer', 'B');
hero.build('archer', 'C');
hero.build('mage', 'A');
hero.build('frost', 30, 75);
hero.build('frost', 30, 26);
hero.build('cannon', 42,79);
hero.build('cannon', 42, 73);
hero.build('cannon', 42, 55);
hero.build('cannon', 42, 52);
hero.build('cannon', 42, 32);
hero.build('cannon', 42, 25);
hero.build('archer', 29, 73);
hero.build('archer', 29, 55);
hero.build('archer', 29, 52);
hero.build('archer', 29, 32);